// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovenaTracker.Infrastructure.Data;

#nullable disable

namespace NovenaTracker.Infrastructure.Migrations
{
    [DbContext(typeof(NovenaTrackerDbContext))]
    [Migration("20260117161006_InitialCreateWithWenantyNovena")]
    partial class InitialCreateWithWenantyNovena
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("NovenaTracker.Domain.Entities.Novena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DaysDuration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Novenas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DaysDuration = 9,
                            Description = "Nowenna do Wenantego Katarzyńca to 9-dniowa modlitwa (nowenna od łac. novem - dziewięć), przez którą wierni proszą o łaski za wstawiennictwem Sługi Bożego o. Wenantego, franciszkanina, często w intencjach związanych z pracą, finansami i trudnymi sprawami, a także za dusze w czyśćcu cierpiące, gdyż sam o. Wenanty był ich gorliwym orędownikiem.",
                            Title = "Dziewięciodniowa nowenna za wstawiennictwem Sługi Bożego o.Wenantego Katarzyńca"
                        });
                });

            modelBuilder.Entity("NovenaTracker.Domain.Entities.NovenaCompletion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NovenaDayPrayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NovenaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NovenaDayPrayerId")
                        .IsUnique();

                    b.HasIndex("NovenaId");

                    b.ToTable("NovenaCompletions");
                });

            modelBuilder.Entity("NovenaTracker.Domain.Entities.NovenaDayPrayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NovenaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrayerText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrayerTitle")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NovenaId", "DayNumber");

                    b.ToTable("NovenaDayPrayers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayNumber = 0,
                            NovenaId = 1,
                            PrayerText = "Boże w Trójcy Jedyny, bądź uwielbiony za wszelkie dobra, którymi napełniłeś sługę Twego Wenantego; on przez życie według rad ewangelicznych i gorliwą posługę kapłańską w Kościele stał się przykładem dla Twoich wiernych. Wynieś, Panie, tego sługę Twego na ołtarze, abyśmy lepiej mogli Tobie służyć, mnie zaś udziel łaski, o którą pokornie proszę za jego wstawiennictwem. Przez Chrystusa Pana naszego. Amen.",
                            PrayerTitle = "Modlitwa początkowa"
                        },
                        new
                        {
                            Id = 2,
                            DayNumber = 1,
                            NovenaId = 1,
                            PrayerText = "[Treść modlitwy z https://wenanty.pl/nowenna/]",
                            PrayerTitle = "Dzień 1 – Dobre życie"
                        },
                        new
                        {
                            Id = 3,
                            DayNumber = 2,
                            NovenaId = 1,
                            PrayerText = "[Treść modlitwy z https://wenanty.pl/nowenna/]",
                            PrayerTitle = "Dzień 2 – Łaska"
                        },
                        new
                        {
                            Id = 4,
                            DayNumber = 3,
                            NovenaId = 1,
                            PrayerText = "[Treść modlitwy z https://wenanty.pl/nowenna/]",
                            PrayerTitle = "Dzień 3 – Unikanie grzechów"
                        },
                        new
                        {
                            Id = 5,
                            DayNumber = 4,
                            NovenaId = 1,
                            PrayerText = "[Treść modlitwy z https://wenanty.pl/nowenna/]",
                            PrayerTitle = "Dzień 4 – Cierpienie"
                        },
                        new
                        {
                            Id = 6,
                            DayNumber = 5,
                            NovenaId = 1,
                            PrayerText = "[Treść modlitwy z https://wenanty.pl/nowenna/]",
                            PrayerTitle = "Dzień 5 – Wiara"
                        },
                        new
                        {
                            Id = 7,
                            DayNumber = 6,
                            NovenaId = 1,
                            PrayerText = "[Treść modlitwy z https://wenanty.pl/nowenna/]",
                            PrayerTitle = "Dzień 6 – Nadzieja"
                        },
                        new
                        {
                            Id = 8,
                            DayNumber = 7,
                            NovenaId = 1,
                            PrayerText = "[Treść modlitwy z https://wenanty.pl/nowenna/]",
                            PrayerTitle = "Dzień 7 – Modlitwa"
                        },
                        new
                        {
                            Id = 9,
                            DayNumber = 8,
                            NovenaId = 1,
                            PrayerText = "[Treść modlitwy z https://wenanty.pl/nowenna/]",
                            PrayerTitle = "Dzień 8 – Maryja"
                        },
                        new
                        {
                            Id = 10,
                            DayNumber = 9,
                            NovenaId = 1,
                            PrayerText = "[Treść modlitwy z https://wenanty.pl/nowenna/]",
                            PrayerTitle = "Dzień 9 – Niebo"
                        });
                });

            modelBuilder.Entity("NovenaTracker.Domain.Entities.NovenaCompletion", b =>
                {
                    b.HasOne("NovenaTracker.Domain.Entities.NovenaDayPrayer", "NovenaDayPrayer")
                        .WithMany("Completions")
                        .HasForeignKey("NovenaDayPrayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NovenaTracker.Domain.Entities.Novena", "Novena")
                        .WithMany("Completions")
                        .HasForeignKey("NovenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Novena");

                    b.Navigation("NovenaDayPrayer");
                });

            modelBuilder.Entity("NovenaTracker.Domain.Entities.NovenaDayPrayer", b =>
                {
                    b.HasOne("NovenaTracker.Domain.Entities.Novena", "Novena")
                        .WithMany("DayPrayers")
                        .HasForeignKey("NovenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Novena");
                });

            modelBuilder.Entity("NovenaTracker.Domain.Entities.Novena", b =>
                {
                    b.Navigation("Completions");

                    b.Navigation("DayPrayers");
                });

            modelBuilder.Entity("NovenaTracker.Domain.Entities.NovenaDayPrayer", b =>
                {
                    b.Navigation("Completions");
                });
#pragma warning restore 612, 618
        }
    }
}
