// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovenaTracker.Infrastructure.Data;

#nullable disable

namespace NovenaTracker.Infrastructure.Migrations
{
    [DbContext(typeof(NovenaTrackerDbContext))]
    partial class NovenaTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("NovenaTracker.Domain.Entities.Novena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DaysDuration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Novenas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DaysDuration = 9,
                            Description = "A nine-day prayer to Our Lady of Perpetual Help",
                            Title = "Novena to Our Lady of Perpetual Help"
                        });
                });

            modelBuilder.Entity("NovenaTracker.Domain.Entities.NovenaCompletion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NovenaDayPrayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NovenaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NovenaDayPrayerId")
                        .IsUnique();

                    b.HasIndex("NovenaId");

                    b.ToTable("NovenaCompletions");
                });

            modelBuilder.Entity("NovenaTracker.Domain.Entities.NovenaDayPrayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NovenaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrayerText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrayerTitle")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NovenaId", "DayNumber");

                    b.ToTable("NovenaDayPrayers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayNumber = 1,
                            NovenaId = 1,
                            PrayerText = "O Mother of Perpetual Help, grant that I may ever invoke your powerful name...",
                            PrayerTitle = "Day 1 - Trust in Mary"
                        },
                        new
                        {
                            Id = 2,
                            DayNumber = 2,
                            NovenaId = 1,
                            PrayerText = "O Mary, you are the hope of Christians, hear the prayer of a sinner who loves you tenderly...",
                            PrayerTitle = "Day 2 - Hope in Mary"
                        },
                        new
                        {
                            Id = 3,
                            DayNumber = 3,
                            NovenaId = 1,
                            PrayerText = "O Mother of Perpetual Help, I come to you with confidence and love...",
                            PrayerTitle = "Day 3 - Love for Mary"
                        });
                });

            modelBuilder.Entity("NovenaTracker.Domain.Entities.NovenaCompletion", b =>
                {
                    b.HasOne("NovenaTracker.Domain.Entities.NovenaDayPrayer", "NovenaDayPrayer")
                        .WithMany("Completions")
                        .HasForeignKey("NovenaDayPrayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NovenaTracker.Domain.Entities.Novena", "Novena")
                        .WithMany("Completions")
                        .HasForeignKey("NovenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Novena");

                    b.Navigation("NovenaDayPrayer");
                });

            modelBuilder.Entity("NovenaTracker.Domain.Entities.NovenaDayPrayer", b =>
                {
                    b.HasOne("NovenaTracker.Domain.Entities.Novena", "Novena")
                        .WithMany("DayPrayers")
                        .HasForeignKey("NovenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Novena");
                });

            modelBuilder.Entity("NovenaTracker.Domain.Entities.Novena", b =>
                {
                    b.Navigation("Completions");

                    b.Navigation("DayPrayers");
                });

            modelBuilder.Entity("NovenaTracker.Domain.Entities.NovenaDayPrayer", b =>
                {
                    b.Navigation("Completions");
                });
#pragma warning restore 612, 618
        }
    }
}
